export const translations = {
    en: {
        // Sidebar tabs
        dashboard: '📊 Dashboard',
        catalog: '🗂️ Catalog Hub',
        sales: '💰 Sales Hub',
        staff: '👥 Staff & Roles',
        settings: '⚙️ Shop Settings',
        logs: '📜 Activity Logs',

        // Dashboard stats
        welcome_back: 'Welcome back',
        today_sales: "Today's Sales",
        today_profit: "Today's Profit",
        month_sales: "Month Sales",
        month_profit: "Month Profit",
        year_sales: "Year Sales",
        year_profit: "Year Profit",
        quick_summary: 'Quick Summary',
        total_orders: 'Total Orders',
        total_revenue: 'Total Revenue',
        total_cost: 'Total Cost',
        total_profit: 'Total Profit',
        today_performance: 'Today Performance',
        month_performance: 'Month Performance',
        year_performance: 'Year Performance',
        loading_analytics: 'Loading analytics...',
        no_sales_data: 'No sales data yet. Make your first sale via POS!',
        today: 'Today',
        
        date_filter: 'Date Filter',
        
        all_time: 'All Time',
        yesterday: 'Yesterday',
        last_7_days: 'Last 7 Days',
        last_1_month: 'Last 1 Month',
        custom_range: 'Custom Range',
        date_all_time: 'Date: All Time',
        date_today: 'Date: Today',
        date_yesterday: 'Date: Yesterday',
        date_last_7_days: 'Date: Last 7 Days',
        date_last_1_month: 'Date: Last 1 Month',
        date_custom_range: 'Date: Custom Range',
        
        
        
        // POS & Cart
        cart_items: 'Cart Items',
        checkout: 'Checkout',
        complete_pos_sale: 'Complete POS Sale',
        payment_method: 'Payment Method',
        customer_name: 'Customer Name',
        customer_email: 'Customer Email',
        discount: 'Discount',
        tax: 'Tax',
        total_amount: 'Total Amount',
        
        // Log & common labels
        cashier: 'Cashier',
        invoice: 'Invoice',
        date: 'Date',
        actions: 'Actions',
        view_invoice: 'View Invoice',
        search: 'Search',
        clear: 'Clear',
        export_report: 'Export Report',
        products: 'Products',
        categories: 'Categories',
        brands: 'Brands',
        name: 'Name',
        price: 'Price',
        stock: 'Stock',
        status: 'Status',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        add: 'Add',
    },
    bn: {
        // Sidebar tabs
        dashboard: '📊 ড্যাশবোর্ড',
        catalog: '🗂️ ক্যাটালগ হাব',
        sales: '💰 সেলস হাব',
        staff: '👥 স্টাফ ও রোলস',
        settings: '⚙️ শপ সেটিংস',
        logs: '📜 অ্যাক্টিভিটি লগস',

        // Dashboard stats
        welcome_back: 'স্বাগতম',
        today_sales: 'আজকের বিক্রি',
        today_profit: 'আজকের লাভ',
        month_sales: 'মাসিক বিক্রি',
        month_profit: 'মাসিক লাভ',
        year_sales: 'বার্ষিক বিক্রি',
        year_profit: 'বার্ষিক লাভ',
        quick_summary: 'সংক্ষিপ্ত বিবরণ',
        total_orders: 'মোট অর্ডার',
        total_revenue: 'মোট রাজস্ব',
        total_cost: 'মোট খরচ',
        total_profit: 'মোট লাভ',
        today_performance: 'আজকের পারফরম্যান্স',
        month_performance: 'মাসিক পারফরম্যান্স',
        year_performance: 'বার্ষিক পারফরম্যান্স',
        loading_analytics: 'বিশ্লেষণ লোড হচ্ছে...',
        no_sales_data: 'এখনও কোনও বিক্রির তথ্য নেই। পিওএস দিয়ে প্রথম বিক্রিটি করুন!',
        today: 'আজ',
        
        date_filter: 'তারিখ ফিল্টার',
        
        all_time: 'সব সময়',
        yesterday: 'গতকাল',
        last_7_days: 'গত ৭ দিন',
        last_1_month: 'গত ১ মাস',
        custom_range: 'নির্দিষ্ট সময়সীমা',
        date_all_time: 'তারিখ: সব সময়',
        date_today: 'তারিখ: আজ',
        date_yesterday: 'তারিখ: গতকাল',
        date_last_7_days: 'তারিখ: গত ৭ দিন',
        date_last_1_month: 'তারিখ: গত ১ মাস',
        date_custom_range: 'তারিখ: নির্দিষ্ট সময়সীমা',
        
        

        // POS & Cart
        cart_items: 'কার্ট আইটেম',
        checkout: 'চেকআউট',
        complete_pos_sale: 'পিওএস বিক্রি সম্পন্ন করুন',
        payment_method: 'পেমেন্ট পদ্ধতি',
        customer_name: 'গ্রাহকের নাম',
        customer_email: 'গ্রাহকের ইমেইল',
        discount: 'ডিসকাউন্ট',
        tax: 'ট্যাক্স',
        total_amount: 'মোট পরিমাণ',

        // Log & common labels
        cashier: 'ক্যাশিয়ার',
        invoice: 'ইনভয়েস',
        date: 'তারিখ',
        actions: 'অ্যাকশন',
        view_invoice: 'ইনভয়েস দেখুন',
        search: 'অনুসন্ধান',
        clear: 'মুছুন',
        export_report: 'রিপোর্ট এক্সপোর্ট করুন',
        products: 'পণ্য',
        categories: 'ক্যাটাগরি',
        brands: 'ব্র্যান্ড',
        name: 'নাম',
        price: 'মূল্য',
        stock: 'স্টক',
        status: 'স্ট্যাটাস',
        edit: 'সম্পাদনা',
        delete: 'মুছুন',
        save: 'সংরক্ষণ করুন',
        cancel: 'বাতিল করুন',
        add: 'যুক্ত করুন',
    }
};
